# Pre-commit hooks for AWS SSM Data Fetcher
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  # General code quality and safety
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        description: Trim trailing whitespace
      - id: end-of-file-fixer
        description: Ensure files end with a newline
      - id: check-yaml
        description: Check YAML file syntax
      - id: check-json
        description: Check JSON file syntax
      - id: check-toml
        description: Check TOML file syntax
      - id: check-merge-conflict
        description: Check for merge conflict markers
      - id: check-added-large-files
        description: Prevent large files from being committed
        args: ['--maxkb=10240']  # 10MB limit

  # Python code formatting (matches CI pipeline)
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        description: Format Python code with Black
        args: ['--config=pyproject.toml']

  # Python import sorting (matches CI pipeline)
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        description: Sort Python imports
        args: ['--settings-path=pyproject.toml']

  # Terraform formatting (matches CI pipeline)
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.1
    hooks:
      - id: terraform_fmt
        description: Format Terraform files
        args: ['--args=-recursive']

  # Python type checking (matches CI pipeline)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        description: Static type checking with mypy
        args: ['--ignore-missing-imports', '--show-error-codes']
        files: '^aws_ssm_fetcher/.*\.py$'
        additional_dependencies: [types-requests, types-PyYAML]

  # Secrets scanning
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        description: Scan for secrets
        args: ['--baseline', '.secrets.baseline']

# Configuration
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: develop
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false
