[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'
extend-exclude = '''
(
  \.git
  | \.venv
  | build
  | dist
)
'''

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
exclude = [
    "lambda_functions/processor/aws_ssm_fetcher/",
    "lambda_functions/data_fetcher/aws_ssm_fetcher/",
    "lambda_functions/report_generator/aws_ssm_fetcher/"
]
